### ISSUE TITLE
Suporte SAAS (multi empresas)

### ISSUE THREAD

**Issue by 1579091** [unkbot/chatwoot-codechat#12]
Atualmente o conector só suporta 1 única empresa ATIVA para recebimento de mensagens.

Até funciona se atrelar o usuário detentor do token do .env para criar o INBOX e gerar o QR Code através dele. Porém esse usuário detentor do TOKEN precisa estar atrelado na empresa em questão, caso ele alterne para outra empresa, automaticamente a anterior para de receber mensagens. Ou seja se tiver 3 empresas, somente 1 estará recebendo as mensagens corretamente (a que o usuário do token pertence atualmente), deixando INBOX indisponível para o recebimento de mensagens (mesmo que permitindo o envio).

O erro:
0|conector  | TypeError: Cannot read properties of undefined (reading 'id')
0|conector  |     at createConversation (/root/chatwoot-codechat/dist/providers/chatwoot/index.js:64:131)
0|conector  |     at runMicrotasks (<anonymous>)
0|conector  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|conector  |     at async eventCodeChat (/root/chatwoot-codechat/dist/events/index.js:102:35)
0|conector  |     at async /root/chatwoot-codechat/dist/app.js:44:22
0|conector  | Error: TypeError: Cannot read properties of undefined (reading 'id')
0|conector  |     at createConversation (/root/chatwoot-codechat/dist/providers/chatwoot/index.js:92:15)
0|conector  |     at runMicrotasks (<anonymous>)
0|conector  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|conector  |     at async eventCodeChat (/root/chatwoot-codechat/dist/events/index.js:102:35)
0|conector  |     at async /root/chatwoot-codechat/dist/app.js:44:22

**Comment by w3nder** [comment]
Olá, irei corrigir.
