### ISSUE TITLE
Não recebo o QRCode na conversa do Chatwoot

### ISSUE THREAD

**Issue by clarcksp** [unkbot/chatwoot-codechat#14]
Olá, bom dia.
Estou instalando o conector juntamente com o chatwoot, faço todo o processo, porém não recebo o QRCode na conversa do Bot via Chatwoot.
No PM2 log me aparece o QRCode e consigo conectar.
Mas durante o log me é apresentado a seguinte mensagem:

`0|conector  | SqliteError: no such table: providers
0|conector  |     at Database.prepare (/home/usuario/chatwoot-codechat/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
0|conector  |     at eventCodeChat (/home/usuario/chatwoot-codechat/dist/events/index.js:89:40)
0|conector  |     at /home/usuario/chatwoot-codechat/dist/app.js:71:55
0|conector  |     at Layer.handle [as handle_request] (/home/usuario/chatwoot-codechat/node_modules/express/lib/router/layer.js:95:5)
0|conector  |     at next (/home/usuario/chatwoot-codechat/node_modules/express/lib/router/route.js:144:13)
0|conector  |     at Route.dispatch (/home/usuario/chatwoot-codechat/node_modules/express/lib/router/route.js:114:3)
0|conector  |     at Layer.handle [as handle_request] (/home/usuario/chatwoot-codechat/node_modules/express/lib/router/layer.js:95:5)
0|conector  |     at /home/usuario/chatwoot-codechat/node_modules/express/lib/router/index.js:284:15
0|conector  |     at param (/home/usuario/chatwoot-codechat/node_modules/express/lib/router/index.js:365:14)
0|conector  |     at param (/home/usuario/chatwoot-codechat/node_modules/express/lib/router/index.js:376:14) {
0|conector  |   code: 'SQLITE_ERROR'
`

Inicialmente fiz a instalação na ultima versão do chatwoot (2.7.1) porém acabei de reinstalar tudo novamente e estou utilizando a versão 2.6.0 que vi neste tutorial: https://www.youtube.com/watch?v=3Y5AIaq4xVQ

Mas em ambos acontece o mesmo erro.

Agradeço o apoio

**Comment by clarcksp** [comment]
Pessoal, refiz a instalação seguindo o tutorial para https.
Agora eu não recebo mais erro de conexão do sqllite porém na mensagem de log do conector vem apenas "Erro ao buscar instância"

**Comment by w3nder** [comment]
Nessa nova versão foi alterada bastante coisa, agora as config da sua caixa de entrada tem que ser feito 

```
curl --location 'http://localhost:1234/create-provider' \
--header 'Content-Type: application/json' \
--data '{
    "account_id": "76598",
    "token": "LrN39bkVbbFRr5H3WBQUzRf3",
    "url": "https://app.chatwoot.com",
    "nameInbox": "SeuNomeSemEspaço"
}'

```

ou fazer uma request para sua url do conector/create-provider do tipo POST passando o data 

você pode criar com os mesmo nome de inbox já existente!

**Comment by clarcksp** [comment]
EU executei este comando. Porém não fiz nenhuma edição.
accound_id seria o ID da conta que vou usar para conectar no meu caso seria 1
token é o token do chatwoot certo?
 A URL seria a do meu servidor?
E nameInbox seria o nome que eu vou criar para  caixa de entrada no chatwoot?

**Comment by clarcksp** [comment]
Complementando a pergunta...
Rodei novamente porém alterando os dados, mas digitei um campo errado.
Quando fui tentar enviar novamente recebi essa msg:
`{"message":"error","error":"Já existe um provider com esse account_id"}r`

**Comment by w3nder** [comment]
Vlw, ajustado!

**Comment by mauriciomagalhaes** [comment]
Tive o mesmo problema de ClarkSP, de nao receber o QRcode.
e enviei via postman
{
    "account_id": "1",
    "token": "CHHdXQSwxRiFPUAeeFYfkPXW",
    "url": "https://localhost:3000",
    "nameInbox": "Empresa"
}

e retornou um 
{
    "message": "ok",
    "info": {
        "changes": 1,
        "lastInsertRowid": 1
    }
}

Mas ao chamar /iniciar pelo bot  +123456

Acontece isso

⚡️[server]: Server is running at http://localhost:1234█
🎉 Evento recebido de 123456
undefined

Dai o Qrcode nao vai para o chatwoot

**Comment by tarikly** [comment]
> Pessoal, refiz a instalação seguindo o tutorial para https. Agora eu não recebo mais erro de conexão do sqllite porém na mensagem de log do conector vem apenas "Erro ao buscar instância"

Qual tutorial?

**Comment by guilhermesommer1** [comment]
> Boa Tarde, Tive o mesmo problema de ClarkSP, de nao receber o QRcode. e enviei via postman { "account_id": "1", "token": "CHHdXQSwxRiFPUAeeFYfkPXW", "url": "https://localhost:3000", "nameInbox": "Empresa" }
> 
> e retornou um { "message": "ok", "info": { "changes": 1, "lastInsertRowid": 1 } }
> 
> Mas ao chamar /iniciar pelo bot +123456
> 
> Acontece isso
> 
> ⚡️[server]: Server is running at [http://localhost:1234█](http://localhost:1234%E2%96%88) 🎉 Evento recebido de 123456 undefined
> 
> Dai o Qrcode nao vai para o chatwoot

Mesmo caso por aqui:

0|conector  | 🎉 Evento recebido de 123456
0|conector  | undefined

**Comment by maciejewshy** [comment]
> > Boa Tarde, Tive o mesmo problema de ClarkSP, de nao receber o QRcode. e enviei via postman { "account_id": "1", "token": "CHHdXQSwxRiFPUAeeFYfkPXW", "url": "https://localhost:3000", "nameInbox": "Empresa" }
> > e retornou um { "message": "ok", "info": { "changes": 1, "lastInsertRowid": 1 } }
> > Mas ao chamar /iniciar pelo bot +123456
> > Acontece isso
> > ⚡️[server]: Server is running at [http://localhost:1234█](http://localhost:1234%E2%96%88) 🎉 Evento recebido de 123456 undefined
> > Dai o Qrcode nao vai para o chatwoot
> 
> Mesmo caso por aqui:
> 
> 0|conector | 🎉 Evento recebido de 123456 0|conector | undefined


> Boa Tarde, Tive o mesmo problema de ClarkSP, de nao receber o QRcode. e enviei via postman { "account_id": "1", "token": "CHHdXQSwxRiFPUAeeFYfkPXW", "url": "https://localhost:3000", "nameInbox": "Empresa" }
> 
> e retornou um { "message": "ok", "info": { "changes": 1, "lastInsertRowid": 1 } }
> 
> Mas ao chamar /iniciar pelo bot +123456
> 
> Acontece isso
> 
> ⚡️[server]: Server is running at [http://localhost:1234█](http://localhost:1234%E2%96%88) 🎉 Evento recebido de 123456 undefined
> 
> Dai o Qrcode nao vai para o chatwoot

Também não recebo o qrcode no chatwoot.
