### ISSUE TITLE
Mensagem Recebida na Caixa Errada

### ISSUE THREAD

**Issue by caoramos** [unkbot/chatwoot-codechat#8]
**Describe the bug**
Quando tem 2 chamados abertos para o mesmo contato utilizando canais diferentes, a mensagem recebida entra somente em uma caixa. O problema só ocorre quando o mesmo contato manda mensagem para 2 caixas cadastradas.

**To Reproduce**
1) Criar 2 Canais com o conector; Codechat1 e CodeChat2.
2) Uma pessoa enviar mensagem para o CodeChat 1.
3) O operador responde, e mantem a conversa ativa.
4) A pessoa pessoa envia mensagem para o Codechat2.
5) A mensagem chega na mesma conversa do CodeChat1 e não abre nova conversa no CodeChat2.
6) Operador responde no chamado já aberto no CodeChat1.
7) A pessoa recebe a mensagem pelo CodeChat1, apesar de ter enviado a mensagem pelo CodeChat2.

**Expected behavior**
Que cada mensagem enviada para CodeChat1 e CodeChat2 gerasse uma nova conversa.

**Desktop (please complete the following information):**
 - Vultr VPS 4VCPUs 8GB RAM

**Comment by Fagner-lourenco** [comment]
Teve o mesmo problema.

**Comment by lindenbergp** [comment]
Aconteceu o mesmo no meu chatwoot, ele nao consegue diferenciar o mesmo contato se o  mesmo contato mandar mensagem para duas caixas de entradas diferentes.

**Comment by francisbreit** [comment]
Sim. mesmo erro comigo! Existe alguma correção para este problema?
